"""add documents table

Revision ID: cca462f9b340
Revises: a1b2c3d4e5f6
Create Date: 2026-05-27 17:07:31.156172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'cca462f9b340'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('uploader_user_id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('gcs_uri', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('checksum', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('gemini_file_id', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('gemini_store_id', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['uploader_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_profile_id'), 'documents', ['profile_id'], unique=False)
    op.create_index(op.f('ix_documents_uploader_user_id'), 'documents', ['uploader_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_uploader_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_profile_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
